nav + router +intit css
WildCodeSchool-2024-09/JS-Paris-P2-BeerContest pull request #1
Opened 2024-11-07 14:46 UTC by Jilano-honor

2024-11-07 15:00 UTC, AudeNec approved these changes
N'hésite pas à mettre des espaces pour aérer ton code par exemple entre les éléments dans ton css, mais pas gênant pour la nav comme le css est tout petit !

2024-11-08 08:50 UTC, mickaellambert requested changes

2024-11-08 08:50 UTC, mickaellambert commented on src/assets/image.png
Peut on avoir un nom d'image un peu plus clair stp ?

2024-11-08 08:50 UTC, mickaellambert commented on src/component/Nav.css
Concernant la PR d'Aude, on peut voir que la nomenclature des classes et ID css n'est pas la même. Et désolé pour toi mais je préfère celle d'Aude. Je te conseille de regarder par rapport à ce qu'elle a fait

2024-11-08 08:50 UTC, mickaellambert commented on src/index.css
> +/* Reset */
Un petit fichier à part pour le reset css ?

2024-11-08 08:50 UTC, mickaellambert commented on src/index.css
> +/* HTML5 display-role reset for older browsers */
Pense à bien supprimer les commentaires inutiles

2024-11-08 08:50 UTC, mickaellambert commented on src/index.css
> +/* Initialisation des fonts. A modifier les tailles de police au besoin */
Si jamais tu veux laisser des commentaires sur des tâches à effectuer, pense à bien les préfixer de TODO

2024-11-08 08:50 UTC, mickaellambert commented on src/main.tsx
> +const router = createBrowserRouter([
Petit saut de ligne entre les imports et les constantes ?

2024-11-08 08:50 UTC, mickaellambert commented on src/pages/Game.tsx
> +export default Game;
Petit saut de ligne entre les composants et l'export ?

2024-11-08 08:50 UTC, mickaellambert commented on src/pages/Home.tsx
> +export default Home;
Pareil, petit saut de ligne entre les composants et l'export

2024-11-08 11:22 UTC, mickaellambert approved these changes

2024-11-08 11:22 UTC, merged