Diverse fix and game ending
WildCodeSchool-2024-09/JS-Paris-P2-BeerContest pull request #9
Opened 2024-11-15 11:05 UTC by AudeNec

2024-11-18 16:20 UTC, Edwige-Roussin approved these changes

2024-11-19 08:58 UTC, mickaellambert requested changes

2024-11-19 08:58 UTC, mickaellambert commented on src/component/GameSet.tsx
> +		let result = "";
```
    if (computerAbv === userAbv) {
        return { result: RESULT_EQUALITY, message: "C'est égalité !" };
    } else if (computerAbv < userAbv) {
        return { result: RESULT_COMPUTER, message: "C'est perdu !" };
    } else {
        return { result: RESULT_USER, message: "C'est gagné !" };
    }
```

2024-11-19 08:58 UTC, mickaellambert commented on src/component/GameSet.tsx
> +			setPopUp(true);
Comme discuter ensemble, peut être simplifier la gestion du début / fin de jeu, et voir pour renommer de maniere plus claire la maniere dont on change le statut d'un jeu

2024-11-19 08:58 UTC, mickaellambert commented on src/component/GameSet.tsx
>  				{decks[0].length > 0 ? (
Peut être revoir la gestion des données en créant un objet decks contenant une propriété `user` et une propriété `computer`

2024-11-19 08:58 UTC, mickaellambert commented on src/component/GameSet.tsx
> +							onKeyDown={() => handleUserCardSelect(beer)}
A tester

2024-11-19 08:58 UTC, mickaellambert commented on src/component/TestButton.tsx
> +const TestButton = () => {
En terme de naming, peut être 'questionnary' ou 'assessment'

2024-11-19 08:58 UTC, mickaellambert commented on src/pages/Game.tsx
> +					msg="welcome"
Faire des constantes avec des valeurs numériques

2024-11-19 12:00 UTC, Jilano-honor approved these changes

2024-11-19 13:55 UTC, merged